### PR TITLE
Cosmetic changes for my own use.

### PR DESCRIPTION
**Pull request by MichaelTiernan**
1. I've renamed the directory this extention lives in to clarifiy who's it is and what it is.
(The previous name 'extentions' implied the dir was part of the existing infrastructure of the project.) 
1. I copied the README and created this markdown version.
1. I also started to fill out some of the content to show what I did to use this extention.

**The author of this extention deserves lots of praise for the work done!**

I also corrected the attribution in the README.md. I didn't like the way the attribution was not "up top".

### CODE REVIEW

**Comment by infrastation** [comment]
@avarrish and @phgrau, would you like to provide any feedback on this change?

**Comment by infrastation** [comment]
It is not completely right to attribute a commit to another author w/o solicitation, but I guess you guys can work something out (and learn new things if required). Thanks for proposing the changes anyway.

**Comment by MichaelTiernan** [comment]
> It is not completely right to attribute a commit to another author w/o solicitation, [...]

As per the README for this repo:
> > A note to the repository editors. When you are committing someone's work (either a new file or a change), take care of listing the author in the git commit properly:
> >
> > git commit --author='John Doe <jd@example.com>'

Should that be changed then? I assumed that the point of that statment was to make sure that the original author's efforts remained properly cedited.

**Comment by infrastation** [comment]
In this case the "work" is the particular change being committed, not all subsequent changes to the file.
The intent is to attribute the commit (that is, the changes) properly. As changes accumulate in a particular file, the lines that were changed later will be attributed to those people who changed them.

In other words, in this case you are both git author and git committer, the previous revision had this bit right.

**Comment by infrastation** [comment]
I have compared the patch files for #37 and #38 and it looks like the commit attribution wasn't the only difference between the two, so I will not propose to merge #37 instead. Although I can reset git author to you in this pull request if you want.

**Pull request closed without merging**
