### PR TITLE
Updated csv_import for compatibility with Racktables version 0.21 new plugin format

### PR DESCRIPTION
**Pull request by matt32106**
I have done the minimum changes to be able to run the plugin with the new format. The basic adds I have tested work but I did not check all addxxx functions for compliance with recent code in racktables.

### CODE REVIEW

**Comment by infrastation** [comment]
Thank you for proposing this contribution. Before I look at the code and make any substantial comments, it would help to tell what is the right home of the CSV import plugin. I have contacted SURFsara (where it originated) helpdesk, let's see what they say.

**Comment by matt32106** [comment]
I thought this was the place where the plugins were kept, no?!

**Comment by infrastation** [comment]
Some plugin authors find it more convenient to keep their work in their own repositories, that's fine. RackTables is a free software.

**Comment by infrastation** [comment]
Hold still, there may be an update for you soon.

**Comment by matt32106** [comment]
Holding still.... :)

**Comment by infrastation** [comment]
The plugin now indeed lives in this repository, please try to rebase your work on the latest master branch.

The tradition is to preserve as much git history as possible, so you might have to split your change into two simple commits (one for a 100% file rename/move and another to apply your changes at the new location) in order for git to understand what you are doing. Sometimes git interprets complex changes as "throw existing file away and add this unrelated new file with no history" if you do not break it down into smaller steps. You would have to try to see what works best. Let me know how it went and if you need help.

Regarding the PHP code, please do not introduce a `SELECT * FROM...` in the code you are adding, instead specify each required column as noted [here](https://wiki.racktables.org/index.php/SourceCode#SQL_code_style_guide).

**Comment by matt32106** [comment]
Ok wilco but I need to check what they changed in the code apart from the licence. Nice of them to align the licence BTW.

**Comment by matt32106** [comment]
@infrastation is it ok like this?

**Comment by matt32106** [comment]
Oops. Need to update the licence part. Still a WIP

**Comment by matt32106** [comment]
@infrastation two questions pls: did you consider adding the issues tab in Github? IMO it would be easier for people to discuss about RT there. Where can I ask questions or find help to add features? (I would like to add the capability to create tags in csvimport but I can't find the relevant source part in RT code and as I am a noob in PHP I don't know how to  trace the code that is executed on the tag page of RT).

**Comment by infrastation** [comment]
I have cleaned these changes on your behalf and accepted them, please see the current master branch and base any future work on it. It turned out, on this occasion git preserved the file history when the commit moved and changed it in one go.

Looking at this cleaner version, I now see the `SELECT * ...` I mentioned before existed before your changes, you did not introduce it.

RackTables uses GitHub to host git repositories and to process pull requests. GitHub issues is better than nothing, but RackTables has a proper [mailing list](https://www.freelists.org/list/racktables-users) for discussion and a proper [bug tracker](https://bugs.racktables.org/) for bug tracking, please use them. Even when it is myself answering a question on the mailing list, many other relevant people are in the loop.

**Comment by matt32106** [comment]
Well, I don't like mailing lists (they clutter my mailbox for things I don't necessarily care about multiply that  by the number of FLOSS projects I follow or contribute too, this is too much) + the software for RT mailing list doesn't like me neither "Error You appear to be a robot. Go back and try again. ".

**Comment by infrastation** [comment]
Feel free to look at it again when it is more convenient for you.

**Pull request merged**
