### PR TITLE
* apply strtolower at ifNames

### PR DESCRIPTION
**Pull request by mdpuma**

### CODE REVIEW

**Comment by infrastation** [comment]
Modifying an array from within a `foreach` is asking for PHP trouble. You probably want `array_walk()` here.

**Comment by github138** [comment]
I've added the shortenIfName function to my development version, which could be found here:
https://github.com/github138/myRT-contribs/blob/develop-0.20.x/snmplive.php

Could someone with Cisco equipment give it a try and give some feedback, please?

**Comment by infrastation** [comment]
I can test it tomorrow on a Cisco switch.

**Comment by infrastation** [comment]
`snmplive.php` seems to require `snmpgeneric.php`, which in turn fails to work on my installation because it cannot include `inc/snmp.php`, likely because of `index.php` being a symlink from within the actual `DocumentRoot` away into the rest of the filesystem. I have spent some time looking if that could be fixed quickly with a declaration that `requireExtraFiles()` could process but `snmp.php` is special in that its contents needs to be loaded before the plugins, so I could not come up with a good solution so far.

**Comment by github138** [comment]
Could you try if something like this would work?

require_once (realpath (dirname (__FILE__)).'/../wwwroot/inc/snmp.php');

**Comment by infrastation** [comment]
Yes, this change makes both scripts work though there are minor inconsistencies here and there. I have tested the latest revision from myRT-contribs on WS-C3560X-24T.

**Comment by github138** [comment]
See commit 4399cfe04dd11738cfa347c65ed4a1e0f9f936bd

**Pull request closed without merging**
