### PR TITLE
New version 0.4.0 of the reports plugin

### PR DESCRIPTION
**Pull request by lrupp**
This is a rewrite of the reports plugin, which currently exists under 
 https://github.com/RackTables/racktables-contribs/tree/master/extensions

It should follow the new [plugin standards](https://wiki.racktables.org/index.php/Plugins) for RackTables.

## Other changes for version 0.4.0:
* Unify Server, Switch and Virtual Machine Reports (maintaining only one function for all)
* allow users to customize the path to the CSS and JS files via config variables ('Configuration' => 'User interface')
* always show: Name, MAC(s), IPv4 and IPv6 addresses, comment and contact information
* additionally show:
  * Type, asset no., location, OEM S/N, HW expire date and OS for servers
  * Type, asset no., location, OEM S/N, HW expire date and OS version for switches
  * OS and Hypervisor (container) for virtual machines
* show MAC addresses also for switches (configurable via config variable 'REPORTS_SHOW_MAC_FOR_SWITCHES')
* enhance CSV filename with the short form of the export (server,switches,vm or custom => export_server_$date.csv)
* create 'mailto' links, if the contact is an Email address

I'm not sure if the old directory should be kept for reference?
At least I'm a fan of removing the old plugin directory, as it's name (extensions) is confusion for it's content (reports). But keeping it should also not harm, so this request is just adding the rewritten part. Please advise.

### CODE REVIEW

**Comment by infrastation** [comment]
The commit discards previous history. Let me know if you need help making it right.

**Comment by lrupp** [comment]
Just to be sure: do you mean that I should have moved the "extensions" folder first and submit my stuff as merge request against the moved folder to keep the history of the plugin intact?

**Comment by infrastation** [comment]
Something along those lines. Treat others like you want to be treated yourself, basically. Let me have a few days to find time to see how the commits could be arranged.

**Comment by lrupp** [comment]
Sorry for bothering, but to me it's unclear who and how to proceed?

Do you expect something from me ?

**Comment by infrastation** [comment]
Hello Lars.

Excuse me for a long delay. I have finally managed to look at this merged pull request once again. My earlier comment that the commit discards old history was wrong because the commit adds new files without removing old files, so there is no problem there. However, this also means that the new history is disjoint from the old history. I suspect this can be fixed in a nice way later, but let this not be a problem of yours -- if I do not manage to do that myself later, this would likely mean the problem isn't important enough to solve.

So to answer your question: no, there is no need for a follow-up in this request. Cheers.

**Pull request merged**
